/**
 * Writes environment.prod.ts from Cloudflare Pages / CI env vars before build.
 * API_URL example: https://silk-and-sage-api.onrender.com/api/v1
 */
const fs = require('fs');
const path = require('path');

const apiUrl = (process.env.API_URL || '/api/v1').replace(/\/$/, '');
const assetsBaseUrl = apiUrl.endsWith('/api/v1')
  ? apiUrl.slice(0, -'/api/v1'.length)
  : apiUrl.replace(/\/api\/v1\/?$/, '');
const stripePublishableKey = process.env.STRIPE_PUBLISHABLE_KEY || '';

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
const content = `// Auto-generated by scripts/generate-env.js — do not edit manually.
export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
  assetsBaseUrl: '${assetsBaseUrl}',
  stripePublishableKey: '${stripePublishableKey}',
};
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log('Generated environment.prod.ts');
console.log('  apiUrl:', apiUrl);
console.log('  assetsBaseUrl:', assetsBaseUrl || '(relative)');
