/**
 * Writes environment.prod.ts and _redirects from Cloudflare Pages / CI env vars before build.
 * API_URL example: https://silk-and-sage.onrender.com/api/v1
 */
const fs = require('fs');
const path = require('path');

const apiUrl = (process.env.API_URL || '/api/v1').replace(/\/$/, '');
const assetsBaseUrl = apiUrl.endsWith('/api/v1')
  ? apiUrl.slice(0, -'/api/v1'.length)
  : apiUrl.replace(/\/api\/v1\/?$/, '');
const stripePublishableKey = process.env.STRIPE_PUBLISHABLE_KEY || '';

const rootDir = path.join(__dirname, '..');
const envPath = path.join(rootDir, 'src', 'environments', 'environment.prod.ts');
const redirectsPath = path.join(rootDir, 'src', '_redirects');

const envContent = `// Auto-generated by scripts/generate-env.js — do not edit manually.
export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
  assetsBaseUrl: '${assetsBaseUrl}',
  stripePublishableKey: '${stripePublishableKey}',
};
`;

fs.writeFileSync(envPath, envContent, 'utf8');

const redirectLines = [];
if (assetsBaseUrl.startsWith('http')) {
  redirectLines.push(`/api/*  ${assetsBaseUrl}/api/:splat  200`);
  redirectLines.push(`/uploads/*  ${assetsBaseUrl}/uploads/:splat  200`);
}
redirectLines.push('/*  /index.html  200');

fs.writeFileSync(redirectsPath, redirectLines.join('\n') + '\n', 'utf8');

console.log('Generated environment.prod.ts');
console.log('  apiUrl:', apiUrl);
console.log('  assetsBaseUrl:', assetsBaseUrl || '(relative)');
console.log('Generated _redirects with', redirectLines.length, 'rule(s)');
