/**
 * Generates src/environments/environment.prod.ts from build-time env vars.
 * Run before `ng build` (see the "build:pages" npm script).
 *
 * Required on the host (e.g. Cloudflare Pages):
 *   API_URL  -> full API base, e.g. https://silk-and-sage.onrender.com/api/v1
 * Optional:
 *   STRIPE_PUBLISHABLE_KEY
 */
const fs = require('fs');
const path = require('path');

const DEFAULT_API_URL = 'https://silk-and-sage.onrender.com/api/v1';
const apiUrl = (process.env.API_URL || DEFAULT_API_URL).replace(/\/+$/, '');
const assetsBaseUrl = apiUrl.replace(/\/api\/v1$/, '');
const stripePublishableKey = process.env.STRIPE_PUBLISHABLE_KEY || '';

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
const content = `// Auto-generated by scripts/generate-env.js — do not edit manually.
export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
  assetsBaseUrl: '${assetsBaseUrl === apiUrl ? '' : assetsBaseUrl}',
  stripePublishableKey: '${stripePublishableKey}',
};
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log('Generated environment.prod.ts');
console.log('  apiUrl:', apiUrl);
console.log('  assetsBaseUrl:', assetsBaseUrl === apiUrl ? '(relative)' : assetsBaseUrl);
