// Auto-generated by scripts/generate-env.js — do not edit manually.
export const environment = {
  production: true,
  apiUrl: 'https://silk-and-sage.onrender.com/api/v1',
  assetsBaseUrl: 'https://silk-and-sage.onrender.com',
  stripePublishableKey: '',
};
